openapi: 3.0.1
info:
  title: User Management System
  description: API documentation for User management system
  contact:
    email: rakeshsinha31@gmail.com
  version: 1.0.0
servers:
  - url: /
tags:
  - name: user
    description: Operations to user
  - name: group
    description: Operations to groups
paths:
  /users:
    get:
      tags:
        - user
      summary: Returns a list of users.
      responses:
        200:
          description: A JSON array of user names
          content: {}
  /createuser/:
    post:
      tags:
        - user
      summary: Create an user object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        201:
          description: A JSON array of created user
          content: {}
  /user/delete/id/:
    delete:
      tags:
        - user
      summary: Delete an user object
      parameters:
        - name: id
          in: path
          required: true
          schema: {}
      responses:
        200:
          description: Deleted successfully
  /groups:
    get:
      tags:
        - group
      summary: Returns a list all groups.
      responses:
        200:
          description: A JSON array of user groups
          content: {}
  /group/create/:
    post:
      tags:
        - group
      summary: Add a new group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        200:
          description: A JSON array of created group
  /group/adduser/:
    post:
      tags:
        - user
      summary: Add an existing user to a group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                group_id:
                  type: integer

      responses:
        200:
          description: A JSON array of created group
  /delete/group/id/:
    delete:
      tags:
        - group
      summary: Delete an empty group
      parameters:
        - name: id
          in: path
          required: true
          schema: {}
      responses:
        200:
          description: Deleted successfully

components: {}
